[tool.poetry]
name = "simpletodo"
version = "0.1.0"
description = "Simple ToDo web-application"
authors = ["Artem Stepanenko <artem@stepanenko.one>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.1.3"
django-bootstrap4 = "^2.3.1"
psycopg2 = "^2.8.6"
<<<<<<< HEAD
rollbar = "^0.15.1"
gunicorn = "^20.0.4"
=======
python-dotenv = "^0.15.0"
>>>>>>> develop

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.14.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
