[tool.poetry]
name = "SimpleToDo"
version = "0.1.0"
description = "This is a simple ToDo application"
authors = ["Artem Stepanenko <artem@stepanenko.one>"]

[tool.poetry.dependencies]
python = "^3.7"
gunicorn = "^20.0.4"
Django = "^3.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
